"""Added authentication to Articles DB

Revision ID: 2f837bd9f6ab
Revises: 1cdf9db92a4e
Create Date: 2023-07-01 17:56:47.404865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f837bd9f6ab'
down_revision = '1cdf9db92a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_authenticated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('is_authenticated')

    # ### end Alembic commands ###
