"""Deleted column

Revision ID: 49fc0b2b1a80
Revises: 9a99b9c78397
Create Date: 2023-07-01 19:16:37.838905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49fc0b2b1a80'
down_revision = '9a99b9c78397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_authenticated', sa.Boolean(), nullable=True))
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_authenticated')

    # ### end Alembic commands ###
